name: Run Danger

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  danger:
    runs-on: ubuntu-latest

    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      DANGER_GITHUB_BEARER_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      DANGER_GITHUB_HOST: github.com
      DANGER_GITHUB_API_BASE_URL: https://api.github.com
      DANGER_OCTOKIT_VERIFY_SSL: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Danger
        run: |
          bundle exec danger
